// <auto-generated />
namespace AssignmentStudent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madeAlumniDonercolumnallowedtobenull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madeAlumniDonercolumnallowedtobenull));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221706296_made AlumniDoner column allowed to be null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
